CC=cc
CFLAGS=-DNDEBUG

.PHONY: clean all

all: fnmib

fnmib: fnmib.o oakpark.o
	${CC} ${CFLAGS} fnmib.o oakpark.o -o fnmib

fnmib.o: fnmib.c oakpark.h
	${CC} ${CFLAGS} -c fnmib.c -o fnmib.o

oakpark.o: oakpark.c oakpark.h
	${CC} ${CFLAGS} -c oakpark.c -o oakpark.o

clean:
	rm -f *.o fnmib
