CC=cc
CFLAGS=-Xc -fast -DNDEBUG

.PHONY: clean all

all: fnmib

fnmib: fnmib.o oakpark.o
	${CC} ${CFLAGS} $^ -o $@

fnmib.o: fnmib.c oakpark.h
	${CC} ${CFLAGS} -c fnmib.c -o $@

oakpark.o: oakpark.c oakpark.h
	${CC} ${CFLAGS} -c oakpark.c -o $@

clean:
	rm -f *.o fnmib
